language: objective-c
osx_image: xcode10.1
xcode_workspace: CITA.xcworkspace
xcode_scheme: CITA
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X
before_install:
  - echo "{\"rpcServer\":\"$TEST_RPC_SERVER\"}" > Tests/Config.json
  - travis_wait pod repo update --silent
